[package]
name = "paddle"
version = "0.1.0"
authors = ["Jakob Meier <inbox@jakobmeier.ch>"]
edition = "2018"
license = "MIT/Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
nuts = "0.1.1"
quicksilver = { git = "https://github.com/jakmeier/quicksilver", default-features = false, features = ["complex_shapes"], rev = "224d88a60b4000f209b12856885dafa18a88339a" }
# div = { path = "../../div" }
div = "0.2.0"
chrono = "0.4.19"
js-sys = "0.3.45"

[dependencies.web-sys]
version = "0.3"
features = [
    "HtmlElement"
]