[package]
name = "paddle"
version = "0.1.0"
authors = ["Jakob Meier <inbox@jakobmeier.ch>"]
edition = "2018"
license = "MIT/Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
nuts = { path = "../nuts" }
div = { path = "../div-rs" }
# nuts = { git = "https://github.com/jakmeier/nuts", rev = "158e3fefa8139b2f1f33cb6c4a460c8ec1efa6c7" }
# nuts = "0.1.1"
# div = "0.2.0"
chrono = "0.4.19"
rand = "0.7"
serde = {version = "1.0", features = ["derive"] }
lyon = { version = "0.13", features = ["extra"] }
wasm-bindgen = "0.2.68"
wasm-bindgen-futures = "0.4.18"
js-sys = "0.3.45"

[dependencies.web-sys]
version = "0.3"
features = [
    "Blob",
    "console",
    "DomRect",
    "Document",
    "Element",
    "FileReader",
    "Headers",
    "HtmlCanvasElement",
    "HtmlElement",
    "HtmlImageElement",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "WebGlBuffer",
    "WebGlProgram",
    "WebGlRenderingContext",
    "WebGlShader",
    "WebGlTexture",
    "WebGlUniformLocation",
    "Window",
]